#!/bin/bash

# if [ $? -eq 0 ]; then

# 	echo "Setting env variables"
# 	CON=http://consul.service.consul:8500/v1/kv/smc
# 	curl -X PUT ${CON}/aws_access_key_id -d ${AWS_ACCESS_KEY_ID}
# 	curl -X PUT ${CON}/aws_secret_access_key -d ${AWS_SECRET_ACCESS_KEY}
# 	curl -X PUT ${CON}/rackspace_key -d ${RACKSPACE_KEY}
# 	curl -X PUT ${CON}/rackspace_username -d ${RACKSPACE_USERNAME}
# 	curl -X PUT ${CON}/shopify_api_key -d ${SHOPIFY_API_KEY}
# 	curl -X PUT ${CON}/shopify_secret -d ${SHOPIFY_SECRET}
# 	curl -X PUT ${CON}/intercom_app_id -d ${INTERCOM_APP_ID}
# 	curl -X PUT ${CON}/intercom_api_key -d ${INTERCOM_API_KEY}

# 	echo "Starting consul-template"
# 	/usr/local/consul-template -config /app/conf/consul.conf
# fi

exec "$@"
